server {
  listen 80;
  listen [::]:80;
  server_name optimize.sajaddaneshmand.com;

  location /.well-known/acme-challenge/ {
    root /home/sajad/development/optimize-financial/infra/nginx/acme;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name optimize.sajaddaneshmand.com;

  ssl_certificate /home/sajad/development/optimize-financial/certbot/config/live/optimize.sajaddaneshmand.com/fullchain.pem;
  ssl_certificate_key /home/sajad/development/optimize-financial/certbot/config/live/optimize.sajaddaneshmand.com/privkey.pem;

  client_max_body_size 50m;

  location /api/ {
    proxy_pass http://127.0.0.1:2030/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://127.0.0.1:2020/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
